### DISCUSSION TITLE
How to use style variables in CSS/SCSS files

### DISCUSSION THREAD

**Discussion by HartiganHM** [twilio-labs/paste#1535] [Q&A] [answered]
Hello, Paste friends!

I've looked through the docs and tried poking around, but haven't been able to figure out a way to use Paste style variables (aka tokens) in our CSS/SCSS files. Would someone be able to share some insight with me or point me in the right direction? I've posted an example below for clarity, but let me know if you need more details. 

Thank you!

```css
@import '~@twilio-paste/core/styles';

body {
  background-colors: $color-background;
}
```
